# Generated by Django 5.0.4 on 2025-04-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('current_age', models.IntegerField()),
                ('date_of_admission', models.DateField()),
                ('age_of_admission', models.IntegerField()),
            ],
        ),
    ]
