# Generated by Django 5.0.4 on 2025-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dentalrecord_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('patient_name', models.CharField(max_length=100)),
                ('prescribed_by', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=50)),
                ('mg_per_kg_per_day', models.CharField(max_length=50)),
                ('dose', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('dwm', models.CharField(max_length=10)),
            ],
        ),
    ]
