# Generated by Django 5.0.4 on 2025-04-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_illness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('medical_type', models.CharField(choices=[('General Checkup', 'General Checkup'), ('Dental', 'Dental'), ('Pediatrics', 'Pediatrics')], max_length=100)),
                ('appointment_date', models.DateField()),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('medic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
