# Generated by Django 5.0.4 on 2025-04-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_appointment_patient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('vaccine', models.CharField(max_length=100)),
                ('dose_no', models.IntegerField()),
                ('date_due', models.DateField()),
                ('age_when_due', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.child')),
            ],
        ),
    ]
